apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "libsql-server.fullname" . }}
  labels: 
    {{- include "libsql-server.labels" . | nindent 4 }}
data:
  # Add your configuration data here
  bottomless_bucket: {{ .Values.libsql.bottomless_bucket }}
  bottomless_endpoint: {{ .Values.libsql.bottomless_endpoint }}
  bottomless_aws_default_region: {{ .Values.libsql.bottomless_aws_default_region }}
  rust_logs: {{ .Values.libsql.rust_logs }}
  sqld_node: {{ .Values.libsql.sqld_node }}
