apiVersion: v1
kind: Secret
metadata:
  name: {{ include "libsql-server.fullname" . }}
  labels: 
    {{- include "libsql-server.labels" . | nindent 4 }}
type: Opaque
data:
  s3AccessKey: {{ .Values.libsql.s3AccessKey | b64enc }}
  s3SecretKey: {{ .Values.libsql.s3SecretKey | b64enc }}
